package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"go.mongodb.org/mongo-driver/v2/bson"

	"github.com/tktaofik/capacity-takehome/api/graph/model"
	"github.com/tktaofik/capacity-takehome/api/internal/store"
)

// SendRequest is the resolver for the sendRequest field.
func (r *mutationResolver) SendRequest(ctx context.Context, toUserID string, tier model.Tier) (*model.Request, error) {
	panic(fmt.Errorf("not implemented: SendRequest - sendRequest"))
}

// AcceptRequest is the resolver for the acceptRequest field.
func (r *mutationResolver) AcceptRequest(ctx context.Context, requestID string) (*model.Contact, error) {
	panic(fmt.Errorf("not implemented: AcceptRequest - acceptRequest"))
}

// DeclineRequest is the resolver for the declineRequest field.
func (r *mutationResolver) DeclineRequest(ctx context.Context, requestID string) (*model.Request, error) {
	panic(fmt.Errorf("not implemented: DeclineRequest - declineRequest"))
}

// MoveContact is the resolver for the moveContact field.
func (r *mutationResolver) MoveContact(ctx context.Context, contactID string, tier model.Tier) (*model.Contact, error) {
	panic(fmt.Errorf("not implemented: MoveContact - moveContact"))
}

// RemoveContact is the resolver for the removeContact field.
func (r *mutationResolver) RemoveContact(ctx context.Context, contactID string) (bool, error) {
	panic(fmt.Errorf("not implemented: RemoveContact - removeContact"))
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	id, err := store.CallerID(ctx)
	if err != nil {
		return nil, err
	}
	var u store.User
	if err := r.Store.Users.FindOne(ctx, bson.M{"_id": id}).Decode(&u); err != nil {
		return nil, fmt.Errorf("me: %w", err)
	}
	return &model.User{ID: u.ID.Hex(), Name: u.Name}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]model.User, error) {
	cur, err := r.Store.Users.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("users: %w", err)
	}
	defer cur.Close(ctx)
	var docs []store.User
	if err := cur.All(ctx, &docs); err != nil {
		return nil, fmt.Errorf("users: %w", err)
	}
	out := make([]model.User, 0, len(docs))
	for _, u := range docs {
		out = append(out, model.User{ID: u.ID.Hex(), Name: u.Name})
	}
	return out, nil
}

// Contacts is the resolver for the contacts field.
func (r *queryResolver) Contacts(ctx context.Context) ([]model.Contact, error) {
	panic(fmt.Errorf("not implemented: Contacts - contacts"))
}

// Capacity is the resolver for the capacity field.
func (r *queryResolver) Capacity(ctx context.Context) (*model.Capacity, error) {
	panic(fmt.Errorf("not implemented: Capacity - capacity"))
}

// IncomingRequests is the resolver for the incomingRequests field.
func (r *queryResolver) IncomingRequests(ctx context.Context) ([]model.Request, error) {
	panic(fmt.Errorf("not implemented: IncomingRequests - incomingRequests"))
}

// OutgoingRequests is the resolver for the outgoingRequests field.
func (r *queryResolver) OutgoingRequests(ctx context.Context) ([]model.Request, error) {
	panic(fmt.Errorf("not implemented: OutgoingRequests - outgoingRequests"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
