package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.94

import (
	"context"
	"fmt"

	"go.mongodb.org/mongo-driver/v2/bson"

	"github.com/tktaofik/capacity-takehome/api/graph/model"
	"github.com/tktaofik/capacity-takehome/api/internal/capacity"
	"github.com/tktaofik/capacity-takehome/api/internal/store"
)

// SendRequest is the resolver for the sendRequest field.
func (r *mutationResolver) SendRequest(ctx context.Context, toUserID string, tier model.Tier) (*model.Request, error) {
	caller, err := store.CallerID(ctx)
	if err != nil {
		return nil, err
	}
	req, err := r.Service.SendRequest(ctx, caller, toUserID, toDomainTier(tier))
	if err != nil {
		return nil, err
	}
	return r.toModelRequest(ctx, *req)
}

// AcceptRequest is the resolver for the acceptRequest field.
func (r *mutationResolver) AcceptRequest(ctx context.Context, requestID string) (*model.Contact, error) {
	caller, err := store.CallerID(ctx)
	if err != nil {
		return nil, err
	}
	contact, err := r.Service.AcceptRequest(ctx, caller, requestID)
	if err != nil {
		return nil, err
	}
	return r.toModelContact(ctx, *contact)
}

// DeclineRequest is the resolver for the declineRequest field.
func (r *mutationResolver) DeclineRequest(ctx context.Context, requestID string) (*model.Request, error) {
	caller, err := store.CallerID(ctx)
	if err != nil {
		return nil, err
	}
	req, err := r.Service.DeclineRequest(ctx, caller, requestID)
	if err != nil {
		return nil, err
	}
	return r.toModelRequest(ctx, *req)
}

// MoveContact is the resolver for the moveContact field.
func (r *mutationResolver) MoveContact(ctx context.Context, contactID string, tier model.Tier) (*model.Contact, error) {
	caller, err := store.CallerID(ctx)
	if err != nil {
		return nil, err
	}
	contact, err := r.Service.MoveContact(ctx, caller, contactID, toDomainTier(tier))
	if err != nil {
		return nil, err
	}
	return r.toModelContact(ctx, *contact)
}

// RemoveContact is the resolver for the removeContact field.
func (r *mutationResolver) RemoveContact(ctx context.Context, contactID string) (bool, error) {
	caller, err := store.CallerID(ctx)
	if err != nil {
		return false, err
	}
	return r.Service.RemoveContact(ctx, caller, contactID)
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	id, err := store.CallerID(ctx)
	if err != nil {
		return nil, err
	}
	var u store.User
	if err := r.Store.Users.FindOne(ctx, bson.M{"_id": id}).Decode(&u); err != nil {
		return nil, fmt.Errorf("me: %w", err)
	}
	return &model.User{ID: u.ID.Hex(), Name: u.Name}, nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]model.User, error) {
	cur, err := r.Store.Users.Find(ctx, bson.M{})
	if err != nil {
		return nil, fmt.Errorf("users: %w", err)
	}
	defer cur.Close(ctx)
	var docs []store.User
	if err := cur.All(ctx, &docs); err != nil {
		return nil, fmt.Errorf("users: %w", err)
	}
	out := make([]model.User, 0, len(docs))
	for _, u := range docs {
		out = append(out, model.User{ID: u.ID.Hex(), Name: u.Name})
	}
	return out, nil
}

// Contacts is the resolver for the contacts field.
func (r *queryResolver) Contacts(ctx context.Context) ([]model.Contact, error) {
	caller, err := store.CallerID(ctx)
	if err != nil {
		return nil, err
	}
	docs, err := r.Store.ContactsFor(ctx, caller)
	if err != nil {
		return nil, fmt.Errorf("contacts: %w", err)
	}
	return r.toModelContacts(ctx, docs)
}

// Capacity is the resolver for the capacity field.
func (r *queryResolver) Capacity(ctx context.Context) (*model.Capacity, error) {
	caller, err := store.CallerID(ctx)
	if err != nil {
		return nil, err
	}
	snap, err := r.Service.Snapshot(ctx, caller)
	if err != nil {
		return nil, fmt.Errorf("capacity: %w", err)
	}

	// Every tier is reported, including the empty ones, so the client can render
	// the whole ladder without knowing which tiers exist or what they hold.
	tiers := make([]model.TierCapacity, 0, len(capacity.Tiers()))
	for _, t := range capacity.Tiers() {
		limit, _ := snap.Caps.Cap(t)
		tiers = append(tiers, model.TierCapacity{
			Tier: toModelTier(t),
			Used: snap.Counts[t],
			Cap:  limit,
		})
	}
	return &model.Capacity{
		BudgetUsed: snap.Counts.Total(),
		BudgetCap:  snap.Caps.Budget,
		Tiers:      tiers,
	}, nil
}

// IncomingRequests is the resolver for the incomingRequests field.
func (r *queryResolver) IncomingRequests(ctx context.Context) ([]model.Request, error) {
	caller, err := store.CallerID(ctx)
	if err != nil {
		return nil, err
	}
	// The inbox is what still needs an answer. Answered requests leave it.
	docs, err := r.Store.RequestsWhere(ctx, bson.M{"toId": caller, "status": store.RequestPending})
	if err != nil {
		return nil, fmt.Errorf("incomingRequests: %w", err)
	}
	return r.toModelRequests(ctx, docs)
}

// OutgoingRequests is the resolver for the outgoingRequests field.
func (r *queryResolver) OutgoingRequests(ctx context.Context) ([]model.Request, error) {
	caller, err := store.CallerID(ctx)
	if err != nil {
		return nil, err
	}
	// Declines are kept here, unlike the inbox: the sender is the one person who
	// otherwise never finds out what happened to their request.
	docs, err := r.Store.RequestsWhere(ctx, bson.M{
		"fromId": caller,
		"status": bson.M{"$in": []store.RequestStatus{store.RequestPending, store.RequestDeclined}},
	})
	if err != nil {
		return nil, fmt.Errorf("outgoingRequests: %w", err)
	}
	return r.toModelRequests(ctx, docs)
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
