// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

// Note that budgetUsed may legally exceed budgetCap (a lowered cap, a merge).
// Nothing may assume used <= cap.
type Capacity struct {
	BudgetUsed int            `json:"budgetUsed"`
	BudgetCap  int            `json:"budgetCap"`
	Tiers      []TierCapacity `json:"tiers"`
}

type Contact struct {
	ID string `json:"id"`
	// The other person in the pair.
	User      *User     `json:"user"`
	Tier      Tier      `json:"tier"`
	CreatedAt time.Time `json:"createdAt"`
}

type Mutation struct {
}

type Query struct {
}

type Request struct {
	ID        string        `json:"id"`
	From      *User         `json:"from"`
	To        *User         `json:"to"`
	Tier      Tier          `json:"tier"`
	Status    RequestStatus `json:"status"`
	CreatedAt time.Time     `json:"createdAt"`
}

type TierCapacity struct {
	Tier Tier `json:"tier"`
	Used int  `json:"used"`
	Cap  int  `json:"cap"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type RequestStatus string

const (
	RequestStatusPending  RequestStatus = "PENDING"
	RequestStatusAccepted RequestStatus = "ACCEPTED"
	RequestStatusDeclined RequestStatus = "DECLINED"
)

var AllRequestStatus = []RequestStatus{
	RequestStatusPending,
	RequestStatusAccepted,
	RequestStatusDeclined,
}

func (e RequestStatus) IsValid() bool {
	switch e {
	case RequestStatusPending, RequestStatusAccepted, RequestStatusDeclined:
		return true
	}
	return false
}

func (e RequestStatus) String() string {
	return string(e)
}

func (e *RequestStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RequestStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RequestStatus", str)
	}
	return nil
}

func (e RequestStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RequestStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RequestStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Tier string

const (
	TierPartner Tier = "PARTNER"
	TierCrew    Tier = "CREW"
	TierCircle  Tier = "CIRCLE"
)

var AllTier = []Tier{
	TierPartner,
	TierCrew,
	TierCircle,
}

func (e Tier) IsValid() bool {
	switch e {
	case TierPartner, TierCrew, TierCircle:
		return true
	}
	return false
}

func (e Tier) String() string {
	return string(e)
}

func (e *Tier) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Tier(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Tier", str)
	}
	return nil
}

func (e Tier) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Tier) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Tier) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
